# Change 'comments' to true for Disqus comments
disqus:
 comments: false
 disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-159293282-1'

menu:
- {name: 'About', folder: 'pages', file: 'about'}
- {name: 'Projects', folder: 'pages', file: 'projects'}
- {name: 'Journalism', folder: 'pages', file: 'journalism'}
- {name: 'Poetry', folder: 'pages', file: 'poetry'}
- {name: 'Short Stories', folder: 'pages', file: 'shortstories'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/ollylawson15'}
- {icon: 'facebook', link: 'https://www.facebook.com/olly.lawson2'}
- {icon: 'instagram', link: 'https://www.instagram.com/ollylawson15/'}
# - {icon: 'envelope', link: ''} #
# - {icon: 'rss-square', link: 'feed.xml'} #
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
